"""add processing status

Revision ID: 4ecd7245c26a
Revises: 1a9c198d33d4
Create Date: 2026-04-13 12:38:37.221059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ecd7245c26a'
down_revision = '1a9c198d33d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processing_status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.drop_column('processing_status')

    # ### end Alembic commands ###
